# Generated by Django 5.2.15 on 2026-06-13 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_article_favorites_article_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollution_type', models.CharField(choices=[('plastic', '塑膠與一般垃圾'), ('oil', '油污污染'), ('chemical', '工業或化學廢水'), ('other', '其他民生污染')], max_length=20, verbose_name='污染類型')),
                ('location', models.CharField(max_length=250, verbose_name='通報地點')),
                ('description', models.TextField(verbose_name='詳細描述')),
                ('image', models.ImageField(upload_to='pollution_pics/', verbose_name='現場照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通報時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
